### ISSUE TITLE
@sanity/types imageHotspot declare module not working

### ISSUE THREAD

**Issue by rafaelderolez** [sanity-io/sanity-plugin-hotspot-array#16]
The module [declaration](https://github.com/sanity-io/sanity-plugin-hotspot-array/blob/main/src/plugin.tsx#L13C1-L17C2) to allow `imageHotspot` into ArrayOptions does not seem to work.

### Schema
```typescript
defineField({
  name: 'hotspots',
  type: 'array',
  options: {
    imageHotspot: { 
      imagePath: 'image',
      descriptionPath: 'label',
    },
  },
  of: [
    {
      // spot object here
    }
  ]
})
```

### Error
I get the following TypeScript error:
```
Type '{ imageHotspot: { imagePath: string; descriptionPath: string; }; }'
is not assignable to type 'ArrayOptions<unknown>'.

Object literal may only specify known properties, and 'imageHotspot'
does not exist in type 'ArrayOptions<unknown>'.
```

When adding the declaration manually into my project, the error above disappears.
```typescript
import { ImageHotspotOptions } from 'sanity-plugin-hotspot-array';

declare module '@sanity/types' {
  export interface ArrayOptions {
    imageHotspot?: ImageHotspotOptions
  }
}
```

### Relevant dependencies:
```json
"sanity": "^3.16.4"
"typescript": "^5.2.2"
"sanity-plugin-hotspot-array": "^1.0.1",
```

**Comment by piersolenski** [comment]
I don't know who this @rafaelderolez guy is but he always writes such great, concise issues. Cheers @rafaelderolez, you're doing the Lord's work.

**Comment by ciruz** [comment]
@rafaelderolez we had the same error, after updating sanity to `3.20.2` the error is finally gone.

**Comment by rafaelderolez** [comment]
> @rafaelderolez we had the same error, after updating sanity to `3.20.2` the error is finally gone.

@ciruz You're right! I was able to remove the manual `declare module` previously mentioned without errors. Closing!

**Comment by piersolenski** [comment]
I'm not sure who this @rafaelderolez guy is, but the way he closes an issue just gets my juices going. Thanks, @rafaelderolez .
