### ISSUE TITLE
Options no longer correctly typed

### ISSUE THREAD

**Issue by jkananen** [sanity-io/sanity-plugin-hotspot-array#18]
As of Sanity 3.27.0, a field's `options` with `imageHotspot` gives a type error `Object literal may only specify known properties, and 'imageHotspot' does not exist in type "ArrayOptions<unknown>' . ts (2353)`.

The problem looks to be in: https://github.com/sanity-io/sanity-plugin-hotspot-array/blob/main/src/plugin.tsx#L13-L17

Note that the readme documents this: https://github.com/sanity-io/sanity-plugin-hotspot-array/blob/main/README.md?plain=1#L57

<img width="815" alt="SCR-20240229-irjd" src="https://github.com/sanity-io/sanity-plugin-hotspot-array/assets/33392773/b06a975e-0e41-4f53-a364-cd44473d09a4">

```
$ sanity versions
@sanity/cli (global)                   3.30.1 (up to date)
@sanity/cli                            3.30.1 (up to date)
@sanity/dashboard                       3.1.6 (up to date)
@sanity/document-internationalization   2.1.0 (up to date)
@sanity/language-filter                 3.2.2 (up to date)
@sanity/table                           1.1.2 (up to date)
@sanity/ui                              1.9.3 (latest: 2.0.7)
@sanity/uuid                            3.0.2 (up to date)
@sanity/vision                         3.30.1 (up to date)
sanity                                 3.30.1 (up to date)
```

**Comment by ricokahler** [comment]
We do try to address this [here](https://github.com/sanity-io/sanity-plugin-hotspot-array/blob/e43bfba6cd37523f495ecb2abc471204fcf96398/src/plugin.tsx#L14-L18). Is this issue still occuring? Let us know and we'll reopen if so.

**Comment by jkananen** [comment]
> We do try to address this [here](https://github.com/sanity-io/sanity-plugin-hotspot-array/blob/e43bfba6cd37523f495ecb2abc471204fcf96398/src/plugin.tsx#L14-L18). Is this issue still occuring? Let us know and we'll reopen if so.

@ricokahler yes still occurring with `"sanity-plugin-hotspot-array": "^2.0.0",` and:

```
@sanity/cli (global)                   3.40.0 (up to date)
@sanity/assist                          3.0.3 (up to date)
@sanity/cli                            3.40.0 (up to date)
@sanity/dashboard                       3.1.6 (up to date)
@sanity/document-internationalization   3.0.0 (up to date)
@sanity/language-filter                 4.0.2 (up to date)
@sanity/table                           1.1.2 (up to date)
@sanity/ui                              2.1.6 (up to date)
@sanity/uuid                            3.0.2 (up to date)
@sanity/vision                         3.40.0 (up to date)
sanity                                 3.40.0 (up to date)
```

**Comment by jkananen** [comment]
This no longer occurs with the just updated sanity version 3.49.0.

Full version list currently:
```
$ sanity versions
@sanity/cli (global)                   3.49.0 (up to date)
@sanity/assist                          2.0.5 (latest: 3.0.4)
@sanity/cli                            3.49.0 (up to date)
@sanity/dashboard                       3.1.6 (up to date)
@sanity/document-internationalization   2.1.2 (latest: 3.0.0)
@sanity/language-filter                 3.2.2 (latest: 4.0.2)
@sanity/table                           1.1.2 (up to date)
@sanity/ui                              2.6.3 (up to date)
@sanity/uuid                            3.0.2 (up to date)
@sanity/vision                         3.49.0 (up to date)
sanity                                 3.49.0 (up to date)
```
