### ISSUE TITLE
Spot Bounds not properly updated on first drag

### ISSUE THREAD

**Issue by applehat** [sanity-io/sanity-plugin-hotspot-array#2]
Short explanation of problem I'm seeing.

The `rect` state in Spot.tsx is getting reset to its default on the first drag of a newly created "spot".

Dragging it again seems to resolve the issue.

Haven't spent any real time tying to solve the issue myself outside of just diagnosing the bug I was seeing.

I've attached a video showing the issue in action. 

https://user-images.githubusercontent.com/262524/147983930-8abfe057-e722-4387-ab9a-6629e5513ab8.mp4

**Comment by SimeonGriggs** [comment]
Thanks for reporting! Fixed in `0.0.3`

**Comment by applehat** [comment]
Super quick!

@SimeonGriggs  Thanks man, confirmed working as expected in my local studio!
