### ISSUE TITLE
Sanity client project id is undefined on imagePath

### ISSUE THREAD

**Issue by Sandynism** [sanity-io/sanity-plugin-hotspot-array#20]
**Describe the bug**

When implementing the image for the hotspots array, the image is not visible due to the Sanity projectId being undefined. Is there a way for me to edit the URL so that the projectId is not undefined? 

Inside an Article.js schema file:
```
  Image({
      name: 'heroImage',
      title: 'Hero Image',
      fieldset: 'articleHeader',
    }),

    //HOTSPOT IMAGE
    {
      name: 'imageHotspots',
      title: 'Image Hotspots',
      type: 'array',
      of: [Hotspot],
      options: {
        imageHotspot: {
          imagePath: `heroImage`,
          tooltip: undefined,
        },
      },
      fieldset: 'articleHeader',
      description:
        'This determines where the hotspots on the article hero image will be placed',
    },
```

**Expected behavior**

The image should be visible to the user on the frontend. This is necessary so that editors can place the hotspots correctly.

**Screenshots**
<img width="1325" alt="311372997-45bfb595-fd23-4e03-85dd-02186fd87cb3" src="https://github.com/sanity-io/sanity-plugin-hotspot-array/assets/31261960/bfb970cf-0ee6-4f3f-bef6-edf168053896">

**Which versions of Sanity are you using?**

```
@sanity/cli (global)        3.36.1 (up to date)
@sanity/cli                 3.25.0 (latest: 3.36.1)
@sanity/color-input          3.1.0 (latest: 3.1.1)
@sanity/dashboard            3.1.6 (up to date)
@sanity/icons                2.8.0 (latest: 2.11.4)
@sanity/image-url            1.0.2 (up to date)
@sanity/production-preview  2.35.3 (up to date)
@sanity/schema              3.25.0 (latest: 3.36.1)
@sanity/ui                   1.9.3 (latest: 2.0.12)
@sanity/util                3.25.0 (latest: 3.36.1)
@sanity/validation          3.14.4 (up to date)
@sanity/vision              3.25.0 (latest: 3.36.1)
sanity                      3.25.0 (latest: 3.36.1)
```

**What operating system are you using?**

- Mac OS 14.3.1

**Which versions of Node.js / npm are you running?**

```
npm 8.19.2
node v18.12.0
```

**Comment by ricokahler** [comment]
This should be fixed in v2. Please let me know otherwise and I can reopen
