### ISSUE TITLE
Spots are not movable once added. 

### ISSUE THREAD

**Issue by Slgoetz** [sanity-io/sanity-plugin-hotspot-array#24]
**Describe the bug**
The spots are not movable once added. If you try to move them they automatically get set to 0,0.

[Screen Recording](https://www.awesomescreenshot.com/video/30921924?key=128db179c0bd75e4bddde26cedf0c2ad)

**To Reproduce**
1. Add spot on an image
2. Move the spot after it has been placed

**Expected behavior**
The spot should move and the x,y coordinates should be updated

**Which versions of Sanity are you using?**
```
@sanity/cli (global)          3.23.4 (latest: 3.56.0)
@sanity/dashboard              4.0.0 (up to date)
@sanity/eslint-config-studio   3.0.1 (latest: 4.0.0)
@sanity/ui                     2.8.8 (up to date)
@sanity/vision                3.56.0 (up to date)
sanity                        3.56.0 (up to date)

-------
sanity-plugin-hotspot-array: ^2.0.0
```

**What operating system are you using?**

Mac OS - Sonoma 14.2.1 (23C71)

**Which versions of Node.js / npm are you running?**
node v18.20.4
npm 10.7.0
yarn 1.22.4

**Comment by Slgoetz** [comment]
I got it working by downgrading Sanity to the following

```
@sanity/cli (global)             3.23.4 (latest: 3.56.0)
@sanity/dashboard                 3.1.6 (latest: 4.0.0)
@sanity/eslint-config-studio      3.0.1 (latest: 4.0.0)
@sanity/orderable-document-list   1.2.1 (up to date)
@sanity/ui                        2.4.0 (latest: 2.8.9)
@sanity/vision                   3.46.1 (latest: 3.56.0)
sanity                           3.46.1 (latest: 3.56.0)
```

**Comment by ootes** [comment]
![hotspot-array](https://github.com/user-attachments/assets/6953b56e-9fd3-412f-b2e1-132b535cfb71)

I am experiencing the same issue. Here are my version details. I am a bit hesitant to downgrade.

`sanity-plugin-hotspot-array@2.0.0`

```
@sanity/cli (global)          3.57.0 (latest: 3.57.4)
@sanity/asset-utils            1.3.0 (up to date)
@sanity/eslint-config-studio   4.0.0 (up to date)
@sanity/vision                3.57.3 (latest: 3.57.4)
sanity                        3.57.3 (latest: 3.57.4)
```

**Comment by ragnsan** [comment]
Also experiencing this issue

`
    "sanity-plugin-hotspot-array": "^2.0.0",
    "sanity": "^3.57.3",
    "next-sanity": "^9.4.7",
`

**Comment by artilishes** [comment]
same issue here

```
@sanity/cli (global)        3.44.0 (latest: 3.61.0)
@sanity/asset-utils          2.0.6 (up to date)
@sanity/image-url            1.0.2 (up to date)
@sanity/preview-url-secret  1.6.21 (up to date)
@sanity/ui                   2.8.9 (up to date)
@sanity/vision              3.61.0 (up to date)
sanity                      3.61.0 (up to date)
```
