### ISSUE TITLE
Page jumps when hotspot conditional fields are enabled

### ISSUE THREAD

**Issue by mzohreh** [sanity-io/sanity-plugin-hotspot-array#6]
I have a boolean field in my schema which shows some additional fields, including fields that use the hotspot plugin. The hotspot plugin is causing the page to jump to the hotspot field when the boolean field is enabled. I When I remove the hotspot fields, there is no jumping. Is there a way to stop the page from jumping?

**Comment by SimeonGriggs** [comment]
Thanks for reporting. We've seen other reports of this as well.
