### ISSUE TITLE
HotSpots positioning on the UI

### ISSUE THREAD

**Issue by ccoroian** [sanity-io/sanity-plugin-hotspot-array#7]
Hello. Has anyone came across the issue where when displaying the HotSpots circles on the UI, with the exact coordinates of X% and Y% coming from Sanity, they do not align to the same locations as defined in sanity on the same image. Our problem is with the Y% that needs adjustment from our side depending on the position. Thanks

**Comment by SimeonGriggs** [comment]
The hotspots are positioned using the full, uncropped size of the image. Is your output image cropped perhaps?

**Comment by ccoroian** [comment]
Hi Simeon,
  Thanks for getting back on this.
  We have solved our issue. It was a problem with how we rendered our main image on the UI.
Thanks,
Cosmin
