### ISSUE TITLE
Parent option is broken in Studio v2.34

### ISSUE THREAD

**Issue by jaska120** [sanity-io/sanity-plugin-hotspot-array#8]
Undocumented feature of using parent field for finding related image introduced in https://github.com/sanity-io/sanity-plugin-hotspot-array/commit/ba5cca3d90a9313610a6e3b5fa07049b3e38e2ee, and later revised in https://github.com/sanity-io/sanity-plugin-hotspot-array/commit/a06bb7cd5d2c9f77049c3811e14fb785d19aed2f is broken in Studio v2.34 due to performance optimizations introduced to core. It is possible that v2.33 is affected as well.

To fix the issue, this plugin should use `withParent` HOC introduced in https://github.com/sanity-io/sanity/pull/3672. Furthermore, the parent option should be documented for this plugin.

I could implement these changes, but would like to receive confirmation if it is ok to do so. This will require some dep updates, since the `withParent` HOC was introduced into the core in v2.34.

**Comment by SimeonGriggs** [comment]
Hey Jaska, that would be great if you could submit a PR 🤩

**Comment by jaska120** [comment]
Please find my PR https://github.com/sanity-io/sanity-plugin-hotspot-array/pull/10, which should close this issue.
